# Python Numpy

In [38]:
import numpy as np

In [39]:
arr= np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [40]:
print(np.__version__)

2.3.3


In [41]:
print(type(arr))

<class 'numpy.ndarray'>


In [42]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [43]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [44]:
print(arr.ndim)

3


In [45]:
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)

[[[[[1 2 3 4 5]]]]]


In [46]:
arr= np.array([1,2,3,4,5])
print(arr[3])

4


In [47]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1,2])

6


In [48]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr[0,1,2])

6


In [49]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1,-1])

6


In [50]:
arr= np.array([1,2,3,4,5])
print(arr[0:2])

[1 2]


In [51]:
arr= np.array([1,2,3,4,5])
print(arr[0:4:2])

[1 3]


In [52]:
print(arr.dtype)

int64


In [53]:
newa=arr.astype('f')
print(newa)

[1. 2. 3. 4. 5.]


In [54]:
x=arr.copy()

In [55]:
arr[0]=6
print(x)

[1 2 3 4 5]


In [56]:
y=arr.view()

In [57]:
arr[0]=1
print(y)

[1 2 3 4 5]


In [58]:
print(y.base)
print(x.base)

[1 2 3 4 5]
None


In [59]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [60]:
newarr= arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [61]:
for i in arr:
    print(i)

[1 2 3]
[4 5 6]


In [62]:
for i in arr:
    for j in i:
        print(j, sep=' ')

1
2
3
4
5
6


In [63]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(arr, flags=['buffered'],op_dtypes=['S']):
    print(i)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')
np.bytes_(b'9')


In [64]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(arr[:, ::2]):
    print(i)

1
2
3
7
8
9


In [65]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i,j in np.ndenumerate(arr):
    print(i, j)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9


In [66]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[8,9]])
arr3=np.concatenate((arr1,arr2),axis=1)
print(arr3)

[[1 2 5 6]
 [3 4 8 9]]


In [67]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[8,9]])
arr3=np.stack((arr1,arr2),axis=1)
print(arr3)

[[[1 2]
  [5 6]]

 [[3 4]
  [8 9]]]


In [68]:
arr=np.array([1,2,3,4,5,6,7,8,9,3,4,5,5,8,1,1])
arr2=np.array_split(arr,5)
print(arr2)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([8, 9, 3]), array([4, 5, 5]), array([8, 1, 1])]


In [69]:
print(np.where(arr==4))

(array([ 3, 10]),)


In [70]:
print(np.searchsorted(arr,0,side='right'))


0


In [71]:
print(np.sort(arr))

[1 1 1 2 3 3 4 4 5 5 5 6 7 8 8 9]


In [73]:
arr1=np.array([[2,1],[4,1]])
print(np.sort(arr1))

[[1 2]
 [1 4]]
